services:

  mysql:
    image: mysql:8.4
    container_name: helpdesk-mysql

    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    volumes:
      - helpdesk-db-data:/var/lib/mysql

    networks:
      - helpdesk-network

    restart: unless-stopped

    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-p${MYSQL_ROOT_PASSWORD}"
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s


  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile

    container_name: helpdesk-backend

    env_file:
      - ./backend/.env.docker

    ports:
      - "5000:5000"

    networks:
      - helpdesk-network

    restart: unless-stopped

    depends_on:
      mysql:
        condition: service_healthy

    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:5000/api/health"
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s


  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: helpdesk-frontend

    ports:
      - "5173:80"

    networks:
      - helpdesk-network

    restart: unless-stopped

    depends_on:
      backend:
        condition: service_healthy


volumes:
  helpdesk-db-data:


networks:
  helpdesk-network:
    driver: bridge