import { Request, Response } from "express";
import { Role } from "@prisma/client";
import { AuthRequest } from "../types";
import { addComment, createNewTicket, deleteTicketById, getAllTickets, getTicketById, takeTicket as takeTicketService, updateTicketById } from "../services/ticket.service";

const current = (req: AuthRequest) => { if (!req.user) throw new Error("Authentication required"); return req.user; };

export const createTicket = async (req: AuthRequest, res: Response) => { try { const u = current(req); const ticket = await createNewTicket(req.body.title, req.body.description, Number(req.body.categoryId), u.id); res.status(201).json({ success: true, message: "Ticket created successfully", ticket }); } catch (e: any) { res.status(400).json({ success: false, message: e.message }); } };
export const getTickets = async (req: AuthRequest, res: Response) => { try { const u = current(req); res.json({ success: true, tickets: await getAllTickets(u.id, u.role) }); } catch (e: any) { res.status(500).json({ success: false, message: e.message }); } };
export const getTicketByIdController = async (req: AuthRequest, res: Response) => { try { const u = current(req); res.json({ success: true, ticket: await getTicketById(Number(req.params.id), u.id, u.role) }); } catch (e: any) { res.status(404).json({ success: false, message: e.message }); } };
export { getTicketByIdController as getTicketById };
export const updateTicket = async (req: AuthRequest, res: Response) => { try { const u = current(req); const ticket = await updateTicketById(Number(req.params.id), u.id, u.role, req.body); res.json({ success: true, message: "Ticket updated successfully", ticket }); } catch (e: any) { res.status(400).json({ success: false, message: e.message }); } };
export const deleteTicket = async (req: AuthRequest, res: Response) => { try { const u = current(req); await deleteTicketById(Number(req.params.id), u.role); res.json({ success: true, message: "Ticket deleted successfully" }); } catch (e: any) { res.status(400).json({ success: false, message: e.message }); } };
export const createComment = async (req: AuthRequest, res: Response) => { try { const u = current(req); const isInternal = Boolean(req.body.isInternal); if (isInternal && u.role === Role.CUSTOMER) return res.status(403).json({ success: false, message: "Customers cannot add internal notes" }); const ticket = await getTicketById(Number(req.params.id), u.id, u.role); if (u.role === Role.AGENT && ticket.assignedToId !== u.id && isInternal) return res.status(403).json({ success: false, message: "Only the assigned agent can add internal notes" }); const comment = await addComment(Number(req.params.id), u.id, req.body.comment, isInternal); res.status(201).json({ success: true, message: "Comment added successfully", comment }); } catch (e: any) { res.status(400).json({ success: false, message: e.message }); } };
export const takeTicket = async (req: AuthRequest, res: Response) => { try { const u = current(req); if (u.role !== Role.AGENT) return res.status(403).json({ success: false, message: "Only agents can take tickets" }); res.json({ success: true, message: "Ticket assigned successfully", ticket: await takeTicketService(Number(req.params.id), u.id) }); } catch (e: any) { res.status(400).json({ success: false, message: e.message }); } };
