import { useEffect,useState } from "react";
import { useNavigate,useParams } from "react-router-dom";
import DashboardLayout from "../layouts/DashboardLayout";
import api,{bodyOf,listOf,messageOf} from "../services/api";
import { Avatar,ErrorState,Icon,LoadingState,PriorityBadge,StatusBadge,formatDate } from "../components/Ui";

export default function AdminTicketDetails(){
 const {id}=useParams();const navigate=useNavigate();const [ticket,setTicket]=useState(null),[agents,setAgents]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[form,setForm]=useState({status:"",priority:"",assignedToId:""}),[saving,setSaving]=useState(false),[deleting,setDeleting]=useState(false);
 const load=async()=>{setLoading(true);setError("");try{const [t,u]=await Promise.all([api.get(`/tickets/${id}`),api.get("/admin/users")]);const value=bodyOf(t).ticket;setTicket(value);setForm({status:value.status,priority:value.priority,assignedToId:value.assignedToId||""});setAgents(listOf(u,"users").filter(x=>x.role==="AGENT"));}catch(e){setError(messageOf(e,"Unable to load ticket."));}finally{setLoading(false)}};useEffect(()=>{load()},[id]);
 const save=async()=>{setSaving(true);try{await api.put(`/tickets/${id}`,{status:form.status,priority:form.priority,assignedToId:form.assignedToId?Number(form.assignedToId):null});await load()}catch(e){setError(messageOf(e,"Unable to update ticket."));}finally{setSaving(false)}};
 const remove=async()=>{if(!window.confirm("Delete this ticket permanently?"))return;setDeleting(true);try{await api.delete(`/tickets/${id}`);navigate("/admin/tickets",{replace:true})}catch(e){setError(messageOf(e,"Unable to delete ticket."));}finally{setDeleting(false)}};
 if(loading)return <DashboardLayout role="ADMIN"><LoadingState text="Loading ticket…"/></DashboardLayout>;
 if(!ticket)return <DashboardLayout role="ADMIN"><ErrorState text={error||"Ticket not found."} onRetry={load}/></DashboardLayout>;
 return <DashboardLayout role="ADMIN"><div className="dashboard"><div className="detail-heading"><div><div className="eyebrow">TICKET #{ticket.id}</div><h1>{ticket.title}</h1><p>{ticket.createdBy?.name||"Customer"} · {ticket.createdBy?.email||""} · {formatDate(ticket.createdAt)}</p></div><button className="btn btn-secondary" onClick={()=>navigate("/admin/tickets")}><Icon name="arrow" size={16}/> Back to tickets</button></div>{error&&<ErrorState text={error}/>}
 <div className="detail-grid"><section className="panel conversation-panel"><div className="ticket-detail-top"><div><PriorityBadge value={ticket.priority}/><StatusBadge value={ticket.status}/></div><button className="btn btn-danger btn-sm" disabled={deleting} onClick={remove}><Icon name="trash" size={15}/>{deleting?"Deleting…":"Delete ticket"}</button></div><div className="original-message"><div className="message-author"><Avatar name={ticket.createdBy?.name||"Customer"} small/><div><strong>{ticket.createdBy?.name||"Customer"}</strong><span>{ticket.createdBy?.email||""} · {formatDate(ticket.createdAt,true)}</span></div></div><p>{ticket.description}</p></div><div className="conversation-list">{(ticket.comments||[]).map(c=><div className={`message ${c.isInternal?"internal-message":""}`} key={c.id}><Avatar name={c.user?.name||"User"} small/><div className="message-body"><div><strong>{c.user?.name||"User"}</strong><span>{c.isInternal?"Internal note":"Reply"} · {formatDate(c.createdAt,true)}</span></div><p>{c.comment}</p></div></div>)}</div></section>
 <aside className="side-stack"><div className="panel"><div className="panel-head"><div><span className="panel-kicker">ADMIN CONTROLS</span><h2>Ticket settings</h2></div></div><label>Status<select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option value="OPEN">Open</option><option value="IN_PROGRESS">In progress</option><option value="RESOLVED">Resolved</option><option value="CLOSED">Closed</option></select></label><label>Priority<select value={form.priority} onChange={e=>setForm({...form,priority:e.target.value})}><option value="LOW">Low</option><option value="MEDIUM">Medium</option><option value="HIGH">High</option><option value="URGENT">Urgent</option></select></label><label>Assign to agent<select value={form.assignedToId} onChange={e=>setForm({...form,assignedToId:e.target.value})}><option value="">Unassigned</option>{agents.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label><button className="btn btn-primary btn-block" disabled={saving} onClick={save}>{saving?"Saving…":"Save changes"}</button></div><div className="panel"><div className="panel-head"><div><span className="panel-kicker">ASSIGNMENT</span><h2>Current owner</h2></div></div><div className="owner-card"><Avatar name={ticket.assignedTo?.name||"Unassigned"}/><div><strong>{ticket.assignedTo?.name||"Unassigned"}</strong><span>{ticket.assignedTo?.email||"No agent assigned"}</span></div></div></div></aside></div></div></DashboardLayout>
}
