import { useEffect,useState } from "react";
import DashboardLayout from "../layouts/DashboardLayout";
import api,{listOf,messageOf} from "../services/api";
import { EmptyState,ErrorState,Icon,LoadingState,PageHeader } from "../components/Ui";

export default function AdminCategories(){
 const [categories,setCategories]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[form,setForm]=useState({name:"",description:""}),[editing,setEditing]=useState(null),[saving,setSaving]=useState(false),[deleting,setDeleting]=useState(null);
 const load=async()=>{setLoading(true);setError("");try{setCategories(listOf(await api.get("/admin/categories"),"categories"));}catch(e){setError(messageOf(e,"Unable to load categories."));}finally{setLoading(false)}};useEffect(()=>{load()},[]);
 const submit=async e=>{e.preventDefault();setSaving(true);setError("");try{if(editing)await api.put(`/admin/categories/${editing}`,form);else await api.post("/admin/categories",form);setForm({name:"",description:""});setEditing(null);await load()}catch(e){setError(messageOf(e,"Unable to save category."));}finally{setSaving(false)}};
 const edit=c=>{setEditing(c.id);setForm({name:c.name,description:c.description||""})};
 const remove=async id=>{if(!window.confirm("Delete this category?"))return;setDeleting(id);try{await api.delete(`/admin/categories/${id}`);await load()}catch(e){setError(messageOf(e,"Unable to delete category."));}finally{setDeleting(null)}};
 return <DashboardLayout role="ADMIN"><div className="dashboard"><PageHeader eyebrow="CATEGORY MANAGEMENT" title="Ticket categories" description="Keep customer requests organized with clear support categories."/>
 {error&&<ErrorState text={error} onRetry={load}/>}<div className="admin-two-col"><section className="panel"><div className="panel-head"><div><span className="panel-kicker">{editing?"EDIT CATEGORY":"NEW CATEGORY"}</span><h2>{editing?"Update category":"Add a category"}</h2></div>{editing&&<button className="icon-button" onClick={()=>{setEditing(null);setForm({name:"",description:""})}}><Icon name="close"/></button>}</div><form className="stack-form" onSubmit={submit}><label>Name<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="e.g. Technical Issue" required/></label><label>Description<textarea rows="5" value={form.description} onChange={e=>setForm({...form,description:e.target.value})} placeholder="When should customers use this category?"/></label><button className="btn btn-primary btn-block" disabled={saving}>{saving?"Saving…":editing?"Save changes":"Create category"}<Icon name="arrow" size={16}/></button></form></section>
 <section className="panel"><div className="panel-head"><div><span className="panel-kicker">ACTIVE CATEGORIES</span><h2>{categories.length} categories</h2></div><button className="icon-button" onClick={load}><Icon name="refresh" size={17}/></button></div>{loading?<LoadingState/>:categories.length?<div className="category-list">{categories.map(c=><div className="category-item" key={c.id}><span className="category-icon"><Icon name="tag" size={18}/></span><div><strong>{c.name}</strong><p>{c.description||"No description added."}</p></div><div className="category-actions"><button className="icon-button" title="Edit" onClick={()=>edit(c)}><Icon name="edit" size={16}/></button><button className="icon-button danger" title="Delete" disabled={deleting===c.id} onClick={()=>remove(c.id)}><Icon name="trash" size={16}/></button></div></div>)}</div>:<EmptyState icon="tag" title="No categories" text="Create a category so customers can classify tickets."/>}</section></div>
 </div></DashboardLayout>
}
