import { useEffect,useState } from "react";
import { useNavigate,useParams } from "react-router-dom";
import DashboardLayout from "../layouts/DashboardLayout";
import api,{bodyOf,messageOf} from "../services/api";
import { Avatar,ErrorState,Icon,LoadingState,PriorityBadge,StatusBadge,formatDate } from "../components/Ui";

export default function AgentTicketDetails(){
 const {id}=useParams();const navigate=useNavigate();const [ticket,setTicket]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState(""),[form,setForm]=useState({status:"",priority:""}),[comment,setComment]=useState(""),[internal,setInternal]=useState(false),[saving,setSaving]=useState(false),[sending,setSending]=useState(false);
 const load=async()=>{setLoading(true);setError("");try{const t=bodyOf(await api.get(`/tickets/${id}`)).ticket;setTicket(t);setForm({status:t.status,priority:t.priority});}catch(e){setError(messageOf(e,"Unable to load ticket."));}finally{setLoading(false)}};useEffect(()=>{load()},[id]);
 const save=async()=>{setSaving(true);try{await api.put(`/tickets/${id}`,{status:form.status,priority:form.priority});await load()}catch(e){setError(messageOf(e,"Unable to update ticket."));}finally{setSaving(false)}};
 const add=async e=>{e.preventDefault();if(!comment.trim())return;setSending(true);try{await api.post(`/tickets/${id}/comments`,{comment:comment.trim(),isInternal:internal});setComment("");setInternal(false);await load()}catch(e){setError(messageOf(e,"Unable to add comment."));}finally{setSending(false)}};
 if(loading)return <DashboardLayout role="AGENT"><LoadingState text="Loading ticket…"/></DashboardLayout>;
 if(!ticket)return <DashboardLayout role="AGENT"><ErrorState text={error||"Ticket not found."} onRetry={load}/></DashboardLayout>;
 return <DashboardLayout role="AGENT"><div className="dashboard"><div className="detail-heading"><div><div className="eyebrow">TICKET #{ticket.id}</div><h1>{ticket.title}</h1><p>Created by {ticket.createdBy?.name||"Customer"} · {formatDate(ticket.createdAt)}</p></div><button className="btn btn-secondary" onClick={()=>navigate("/agent/tickets")}><Icon name="arrow" size={16}/> Back to queue</button></div>{error&&<ErrorState text={error}/>}
 <div className="detail-grid"><section className="panel conversation-panel"><div className="ticket-detail-top"><div><PriorityBadge value={ticket.priority}/><StatusBadge value={ticket.status}/></div>{!ticket.assignedToId&&ticket.status!=="CLOSED"&&<button className="btn btn-primary btn-sm" onClick={async()=>{try{await api.post(`/tickets/${id}/take`);load()}catch(e){setError(messageOf(e,"Unable to take ticket."))}}}>Take ticket</button>}</div><div className="original-message"><div className="message-author"><Avatar name={ticket.createdBy?.name||"Customer"} small/><div><strong>{ticket.createdBy?.name||"Customer"}</strong><span>{ticket.createdBy?.email||""} · {formatDate(ticket.createdAt,true)}</span></div></div><p>{ticket.description}</p></div><div className="conversation-list">{(ticket.comments||[]).map(c=><div className={`message ${c.isInternal?"internal-message":""}`} key={c.id}><Avatar name={c.user?.name||"User"} small/><div className="message-body"><div><strong>{c.user?.name||"User"}</strong><span>{c.isInternal?"Internal note":"Reply"} · {formatDate(c.createdAt,true)}</span></div><p>{c.comment}</p></div></div>)}</div>
 <form className="reply-box" onSubmit={add}><textarea rows="4" value={comment} onChange={e=>setComment(e.target.value)} placeholder={internal?"Write an internal note for the support team…":"Write a reply to the customer…"}/><div><label className="check-control"><input type="checkbox" checked={internal} onChange={e=>setInternal(e.target.checked)}/> Internal note</label><button className="btn btn-primary btn-sm" disabled={sending||!comment.trim()}>{sending?"Sending…":internal?"Add note":"Send reply"}<Icon name="arrow" size={15}/></button></div></form></section>
 <aside className="side-stack"><div className="panel"><div className="panel-head"><div><span className="panel-kicker">UPDATE</span><h2>Ticket controls</h2></div></div><label>Status<select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option value="OPEN">Open</option><option value="IN_PROGRESS">In progress</option><option value="RESOLVED">Resolved</option><option value="CLOSED">Closed</option></select></label><label>Priority<select value={form.priority} onChange={e=>setForm({...form,priority:e.target.value})}><option value="LOW">Low</option><option value="MEDIUM">Medium</option><option value="HIGH">High</option><option value="URGENT">Urgent</option></select></label><button className="btn btn-primary btn-block" disabled={saving} onClick={save}>{saving?"Saving…":"Save changes"}</button></div><div className="panel"><div className="panel-head"><div><span className="panel-kicker">ASSIGNMENT</span><h2>Owner</h2></div></div><div className="owner-card"><Avatar name={ticket.assignedTo?.name||"Unassigned"}/><div><strong>{ticket.assignedTo?.name||"Unassigned"}</strong><span>{ticket.assignedTo?.email||"Take the ticket to assign it to yourself."}</span></div></div></div></aside></div></div></DashboardLayout>
}
